### ISSUE TITLE
Conflicting include guard in sys_time.h

### ISSUE THREAD

**Issue by MelanieT** [iiot2k/pico-lib2#2]
If "sys/time.h" has been included, the include guard will prevent this file to be included as it uses the same define. Suggest replacing the include guards in sys_*.h with SYS_LIB2_* to avoid conflicts.

**Comment by iiot2k** [comment]
Hi Melanie,

Thank you for your hint.
It's been a while since I wrote the libraries.
But I plan to expand the lib2 libraries.
Then I will also take note of your advice.
